# Import

In [1]:
import os
import sys
import copy
import time
import math
import hashlib
import json
from tqdm import tqdm
import pandas as pd
from pathlib import Path
import numpy as np
base = Path('/ix/rbao/Projects/HCC-CBS-175-Hillman-RBao-panCancer-HE/')
data = base.joinpath('results','infer_outputs','tile_dfs')
print(data.exists())

True

In [4]:
df = pd.read_csv(fns[0],
                     sep='\t')

In [5]:
df.head()

,tile,x,y,sz,cur_path,p_pos,pred_cls
0,S08-4387_n5677_x73696_y3136_px224.jpg,73696.0,3136.0,224.0,/scratch/slurm-2203027/results/tiles/S08-4387/...,0.001319,1
1,S08-4387_n5678_x73920_y3136_px224.jpg,73920.0,3136.0,224.0,/scratch/slurm-2203027/results/tiles/S08-4387/...,0.000214,1
2,S08-4387_n5679_x74144_y3136_px224.jpg,74144.0,3136.0,224.0,/scratch/slurm-2203027/results/tiles/S08-4387/...,0.003203,1
3,S08-4387_n5680_x74368_y3136_px224.jpg,74368.0,3136.0,224.0,/scratch/slurm-2203027/results/tiles/S08-4387/...,0.011879,1
4,S08-4387_n5681_x74592_y3136_px224.jpg,74592.0,3136.0,224.0,/scratch/slurm-2203027/results/tiles/S08-4387/...,0.000828,1

In [23]:
print(np.sum(df.p_pos > 0.5), np.sum(df.pred_cls==0))

5165 5165

In [19]:
0.4964/2

0.2482

In [20]:
def tiles_to_area(df):
    n = df.shape[0]
    sz = df.sz[0] * 0.2517 #20x in microns
    area = (n * sz**2) / 1e6 #mm2
    return area

In [25]:
fns = [x for x in data.glob('*.tsv')]
print(len(fns))
p_df = pd.DataFrame([])
for i,fn in enumerate(tqdm(fns)):
    df = pd.read_csv(fn,
                     sep='\t')
    tot_n = df.shape[0]
    pos = np.sum(df.pred_cls == 0)
    per = (pos/tot_n) * 100
    slide = Path(df.cur_path[0]).parts[-1].split('_n')[0] + '.svs'
    p_df.loc[i,'slide'] = slide
    p_df.loc[i,'percent_predicted_tumor'] = per
    p_df.loc[i,'total_area_mm2'] = tiles_to_area(df)
    sub = df.loc[df.pred_cls == 0,:].reset_index(drop=True)
    p_df.loc[i,'pred_tum_area_mm2'] = tiles_to_area(sub)
    # idx = df.pred_cls==0

44

100%|██████████| 44/44 [00:02<00:00, 18.72it/s]

In [31]:
p_df.sort_values('pred_tum_area_mm2',ascending=False).reset_index(drop=True)

            slide  percent_predicted_tumor  total_area_mm2  pred_tum_area_mm2
0   S13-18183.svs                76.542246      162.830575         124.634179
1    S15-5437.svs                42.882177      170.510543          73.118634
2    S16-8435.svs                35.342778      195.209777          68.992558
3     S11-732.svs                34.295936      184.818297          63.385164
4    S08-4387.svs                39.673830      124.551530          49.414362
5   S12-13048.svs                23.224852      154.718291          35.933094
6   S17-19517.svs                21.618611      151.259763          32.700260
7     S08-978.svs                17.450315      163.946332          28.609151
8    S06-4083.svs                11.865095      219.044379          25.989825
9   S10-15984.svs                41.998699       39.092816          16.418474
10  S14-19029.svs                10.393675      156.406231          16.256356
11  S16-16565.svs                 6.050639      230.004863          13.916763
12   S11-3887.svs                67.311378       18.243102          12.279684
13   S06-1488.svs                 6.218778      173.079009          10.763399
14   S09-3466.svs                 4.883611      207.705619          10.143534
15   S19-6421.svs                 6.377950      158.691784          10.121282
16  S16-13917.svs                 5.335068      161.231641           8.601818
17   S11-9800.svs                 5.204043      158.205429           8.233078
18  S11-13837.svs                 3.674536      173.969071           6.392556
19    S15-985.svs                 5.231648      103.536519           5.416666
20  S09-14874.svs                 4.797306       95.351123           4.574285
21   S09-3760.svs                10.008375       45.545769           4.558391
22   S16-8420.svs                 1.785623      186.566634           3.331377
23   S13-1707.svs                 5.853419       32.312447           1.891383
24  S09-13092.svs                 3.781513       45.393187           1.716549
25  S21-31385.svs                 2.202959       57.574328           1.268339
26  S21-16752.svs                 1.172281      107.109484           1.255624
27  S12-17713.svs                 0.759806      159.817078           1.214300
28  S11-11671.svs                 0.868735      136.484725           1.185690
29   S13-5642.svs                 0.556674      187.869940           1.045823
30   S19-5709.svs                17.715877        5.705936           1.010857
31  S15-20919.svs                 0.598776      145.992500           0.874169
32  S17-14732.svs                25.884732        3.143828           0.813771
33  S16-10810.svs                 0.831410       93.672720           0.778805
34   S11-8122.svs                 0.690160       99.947660           0.689798
35  S11-12596.svs                 1.497056       37.795868           0.565825
36  S18-23328.svs                 1.802013       27.165979           0.489534
37  S06-17908.svs                 0.958530       47.755031           0.457746
38   S22-9175.svs                 1.015878       42.243002           0.429137
39  S10-18742.svs                 3.555678       11.532667           0.410065
40  S16-11166.svs                 1.277922       30.595898           0.390992
41  S14-11903.svs                 0.278536      115.266271           0.321058
42  S15-15053.svs                 1.570546       12.346438           0.193906
43   S13-6617.svs                 1.648352        6.363947           0.104900

In [27]:
p_df = p_df.sort_values('percent_predicted_tumor',
                ascending=False).reset_index(drop=True)
p_df.head()
results = base.joinpath('results','infer_outputs')
fn = results.joinpath(
                    'acral_percent_tumor_predictions_%d_slides.csv' % p_df.shape[0]
                    )
print(fn)
p_df.to_csv(fn)

/ix/rbao/Projects/HCC-CBS-175-Hillman-RBao-panCancer-HE/results/infer_outputs/acral_percent_tumor_predictions_44_slides.csv